# Generated by Django 4.1.7 on 2023-02-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя гостя')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('text', models.TextField(max_length=3000, verbose_name='Имя гостя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активно'), ('BLOCKED', 'Заблокировано')], default='ACTIVE', max_length=30, verbose_name='Статус')),
            ],
        ),
    ]
